### PR TITLE
I am interested in using your game on my website. Could you add a license file like the MIT one in this pull request so I know how you want your software used?

### PR DESCRIPTION
**Pull request by jpbida**

### CODE REVIEW

**Comment by SnowOnion** [comment]
Oh! Sorry for late replying. Glad to see you like it. I need to query the author :)

@AlephAlpha what license do you want for your `Mathematica2048`?

**Comment by AlephAlpha** [comment]
@SnowOnion [WTFPL](https://en.wikipedia.org/wiki/WTFPL )

**Comment by SnowOnion** [comment]
@jpbida WTFPL :)

**Comment by jpbida** [comment]
Haha, that is the first time I've seen that license. Even has a wikipedia
page. Thanks!

**Pull request closed without merging**
